### ISSUE TITLE
Update boot-2-docker#dns link in dsh init

### ISSUE THREAD

**Issue by davekopecek** [blinkreaction/drude-d8-testing#7]
Text output at the end of `dsh init` does not reflect doc re-organization in /blinkreaction/boot2docker.

Output currently reads:

````
Alternatively configure wildcard DNS resolution and never edit the hosts file again! Instructions:
https://github.com/blinkreaction/boot2docker-vagrant#dns
````

DNS docs are currently here:

````
https://github.com/blinkreaction/boot2docker-vagrant/blob/develop/docs/networking.md#dns
````

**Comment by lmakarov** [comment]
This has been addressed in https://github.com/blinkreaction/drude-d8-testing/pull/6. Thanks!
